### ISSUE TITLE
Jep build fails with USE_MAPPED_EXCEPTIONS enabled

### ISSUE THREAD

**Issue by lasidaputhunattil** [mrj0/jep#10]
Hi,

My machine configuration is
OS: Windows 7 64 bit
Python: 2.6
Java: jdk1.7.0_51]
Jep: 3.1.0

I extracted the contents of the jep package and ran setup.py install from command line but its failing with following error:

c:\mingw\bin\gcc.exe -mcygwin -mdll -O -Wall -DPACKAGE=jep -DUSE_DEALLOC=1 -DVER
SION="3.0.0" "-IC:\Program Files (x86)\Java\jdk1.7.0_51\include" -Isrc/jep -Ibui
ld/include -IC:\Python26\include -IC:\Python26\PC -c src\jep\pyjarray.c -o build
\temp.win32-2.6\Release\src\jep\pyjarray.o
In file included from src\jep\pyjarray.c:35:
src\jep\winconfig.h:25:1: warning: "VERSION" redefined
<command-line>: warning: this is the location of the previous definition
src\jep\pyjarray.c: In function 'pyjarray_item':
src\jep\pyjarray.c:840: warning: format '%li' expects type 'long int', but argum
ent 3 has type 'Py_ssize_t'
src\jep\pyjarray.c: In function 'pyjarray_new_v':
src\jep\pyjarray.c:113: warning: 'componentClass' may be used uninitialized in t
his function
c:\mingw\bin\gcc.exe -mcygwin -mdll -O -Wall -DPACKAGE=jep -DUSE_DEALLOC=1 -DVER
SION="3.0.0" "-IC:\Program Files (x86)\Java\jdk1.7.0_51\include" -Isrc/jep -Ibui
ld/include -IC:\Python26\include -IC:\Python26\PC -c src\jep\pyjclass.c -o build
\temp.win32-2.6\Release\src\jep\pyjclass.o
In file included from src\jep\pyjclass.c:30:
src\jep\winconfig.h:25:1: warning: "VERSION" redefined
<command-line>: warning: this is the location of the previous definition
src\jep\pyjclass.c: In function 'pyjclass_call':
src\jep\pyjclass.c:291: error: 'classGetExceptions' undeclared (first use in thi
s function)
src\jep\pyjclass.c:291: error: (Each undeclared identifier is reported only once

src\jep\pyjclass.c:291: error: for each function it appears in.)
src\jep\pyjclass.c:301: error: 'exceptions' undeclared (first use in this functi
on)
error: command 'gcc' failed with exit status 1

Can anyone help and tell me what is going wrong here. Any help is appreciated as im trying this from long time.

Thanks

**Comment by ndjensen** [comment]
Can you try this again with Jep 3.3?  3.3 works with msvc, I'm not sure about mingw.

**Comment by ndjensen** [comment]
Looking at this more closely, the line that was failing was inside the block of:
```c
#if USE_MAPPED_EXCEPTIONS
// Jep code here
#endif
```
It appears the code was inadvertently broken on this commit: https://github.com/mrj0/jep/commit/9554276fd4841813a1235e6d51748816374170e4#diff-1e0b5efcd0e508953528a2932e9d525d

All that code was removed in favor of a different style of exception handling in Jep 3.3 on this commit: https://github.com/mrj0/jep/commit/bf831f843f282c83670cc8da3716d5e7d86b860b#diff-1e0b5efcd0e508953528a2932e9d525d

So you could avoid the problem by setting `USE_MAPPED_EXCEPTIONS` to 0, or upgrading to a newer version of Jep.

**Comment by ndjensen** [comment]
Closing since `USE_MAPPED_EXCEPTIONS` was removed in Jep 3.3.
