### ISSUE TITLE
hook.py relies on a class list method that does not belong to ClassEnquirer interface

### ISSUE THREAD

**Issue by matteozanon** [mrj0/jep#16]
I tried to use Jep (3.4 branch) with a custom ClassEnquirer. It turns out that it fails at runtime because hook.py calls the method String[] get(String) which exists as a static method in ClassList but does not belong to the ClassEnquirer interface.

I worked around the problem by adding a method with such signature to my custom ClassEnquirer.

**Comment by ndjensen** [comment]
Good catch, thanks for reporting.  I'll work on a fix on 3.4 branch.

**Comment by ndjensen** [comment]
ClassList predated ClassEnquirer so when I first added ClassEnquirer it was designed to be backwards compatible while allowing for custom use cases.  Anyway, long story short, I fixed it on dev_3.4 branch but renamed the method from get to getClassNames.

**Comment by ndjensen** [comment]
Closing as fixed in 3.4.
