### ISSUE TITLE
No module named jep!!!

### ISSUE THREAD

**Issue by behdad84** [mrj0/jep#18]
Hi,
I am trying to run jep in a spark job (The scala code make a call to jep in every task to solver a distributed problem). I have installed jep on every node in the cluster. But when the job runs, in every tasks, I am seeing the following error. Any idea why this happening?  

Caused by: jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: No module named jep
	at jep.Jep.eval(Jep.java:439)
	at jep.Jep.<init>(Jep.java:275)
	at jep.Jep.<init>(Jep.java:218)
	at jep.Jep.<init>(Jep.java:175)

**Comment by ndjensen** [comment]
Hi, if you're not sure if it's a bug, you should email the mailing list for help before writing a ticket.

Anyway, the error message implies you don't have the jep python module installed.  Typically this is installed in python's site-packages dir, though there are ways to make python look it up in other locations.  So you should check your python's site-packages dir and see if you have a folder named jep in there that contains the jep python files, such as __init__.py, hook.py, version.py, etc.

**Comment by behdad84** [comment]
Thanks. I solved this by using the Jep(Boolean, String) constructor and passing the jep package parent resource as the second argument.

**Comment by ndjensen** [comment]
Ok.  That implies that wherever the jep package was installed to was not on the python module search path.  The second argument of String on the `Jep(boolean, String)` constructor is just manipulating python's `sys.path`.

Here's some related links in case you want to look into it further or anyone else encounters this:
* https://docs.python.org/2/tutorial/modules.html#the-module-search-path
* https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH
* https://docs.python.org/2/library/site.html

**Comment by klesniewski** [comment]
I had the same issue (`No module named jep`) when running the most basic Jep Java application embedding Python. The problem apparently was that I installed Jep in virtualenv and yet it tried to find the module elsewhere. It helped to just set `PYTHONHOME` environment variable ([docs][pythonhome]) pointing at the virtualenv directory (`env` in my case)

[pythonhome]: https://docs.python.org/2/using/cmdline.html#envvar-PYTHONHOME
