### ISSUE TITLE
cannot build jep.dll

### ISSUE THREAD

**Issue by st20085** [mrj0/jep#26]
Hello

Sorry for my english ;-)
I used Window 7 64bits, a jdk1.6.0_45 32bits, python 2.7 32 bits
I have downloaded Jep and do "python setup.py build" but I dont have a jep.dll (in build\lib.win32-2.7 folder, I have only jep.exp, jep.lib, jep.pyd and jep folder).

Here is the last traces

C:\Users\Cyril\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:D:\\jdk1.6.0_45\\lib\\ /LIBPATH:D:\\Python27\\libs /LIBPATH:D:\\P
ython27\\PCbuild jvm.lib python27.lib build\temp.win32-2.7\Release\src\jep\invocationhandler.obj build\temp.win32-2.7\Release\src\jep\jep.obj build\temp.win32-2.7\Release\src\jep\pyembed.obj build\tem
p.win32-2.7\Release\src\jep\pyjarray.obj build\temp.win32-2.7\Release\src\jep\pyjclass.obj build\temp.win32-2.7\Release\src\jep\pyjcollection.obj build\temp.win32-2.7\Release\src\jep\pyjfield.obj buil
d\temp.win32-2.7\Release\src\jep\pyjiterable.obj build\temp.win32-2.7\Release\src\jep\pyjiterator.obj build\temp.win32-2.7\Release\src\jep\pyjlist.obj build\temp.win32-2.7\Release\src\jep\pyjmap.obj b
uild\temp.win32-2.7\Release\src\jep\pyjmethod.obj build\temp.win32-2.7\Release\src\jep\pyjmethodwrapper.obj build\temp.win32-2.7\Release\src\jep\pyjobject.obj build\temp.win32-2.7\Release\src\jep\util
.obj build\temp.win32-2.7\Release\src\jep\python\jep_object.obj /OUT:build\lib.win32-2.7\jep.pyd /MANIFESTFILE:build\temp.win32-2.7\Release\src\jep\jep.pyd.manifest /MANIFEST
   Creating library build\lib.win32-2.7\jep.lib and object build\lib.win32-2.7\jep.exp
pyjiterator.obj : warning LNK4217: locally defined symbol _PyJobject_Type imported in function _pyjiterator_new
pyjobject.obj : warning LNK4217: locally defined symbol _PyJmap_Type imported in function _pyjobject_init_subtypes
pyjobject.obj : warning LNK4217: locally defined symbol _PyJlist_Type imported in function _pyjobject_init_subtypes
pyjobject.obj : warning LNK4217: locally defined symbol _PyJcollection_Type imported in function _pyjobject_init_subtypes
pyjobject.obj : warning LNK4217: locally defined symbol _PyJiterable_Type imported in function _pyjobject_init_subtypes
pyjobject.obj : warning LNK4217: locally defined symbol _PyJclass_Type imported in function _pyjobject_new_class
C:\Users\Cyril\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\WinSDK\Bin\mt.exe -nologo -manifest build\temp.win32-2.7\Release\src\jep\jep.pyd.manifest -outputresource:build\lib.win
32-2.7\jep.pyd;2
running build_scripts
creating build\scripts-2.7
copying and adjusting src\scripts\jep.bat -> build\scripts-2.7

If you have any idea
Thanks a lot
Cyril

**Comment by ndjensen** [comment]
Hi, the `python setup.py install` step renames the jep.pyd file to jep.dll.  See this section from the wiki: https://github.com/mrj0/jep/wiki/Windows#running-the-build

You can also rename the jep.pyd file to jep.dll if you're packaging it up in some other way.

**Comment by ndjensen** [comment]
I will look into moving the rename step to part of the `build` command instead of the `install` command.  That should help alleviate confusion.

**Comment by st20085** [comment]
Many thanks

**Comment by vinothkumartc** [comment]
Hello,
Im too facing the similar issue.
We are using windows 64bit and python 2.7.
On installing jep by rurnning setup.py install         there is no jep.dll or jep.pyd created.
Below is the log from the run, Can someone guide us 

C:\vinoth\squish-5\python\Lib\jep>python setup.py install
numpy not found, running without numpy support
running install
running build
running setup_java
Using JAVA_HOME: C:\Program Files\Java\jdk1.7.0_67
running build_java
C:\Program Files\Java\jdk1.7.0_67\bin\javac.exe -deprecation -d build\java -clas
spath src src\jep\ClassEnquirer.java src\jep\ClassList.java src\jep\InvocationHa
ndler.java src\jep\Jep.java src\jep\JepConfig.java src\jep\JepException.java src
\jep\JepScriptEngine.java src\jep\JepScriptEngineFactory.java src\jep\NamingConv
entionClassEnquirer.java src\jep\NDArray.java src\jep\Proxy.java src\jep\Run.jav
a src\jep\Util.java src\jep\python\PyClass.java src\jep\python\PyModule.java src
\jep\python\PyObject.java
C:\Program Files\Java\jdk1.7.0_67\bin\javac.exe -deprecation -d build\java\test
-classpath build\java;src src\jep\test\Test.java src\jep\test\TestBoxing.java sr
c\jep\test\TestGetByteArray.java src\jep\test\TestMemoryLeaks.java src\jep\test\
numpy\TestNumpy.java src\jep\test\numpy\TestNumpyAny.java src\jep\test\numpy\Tes
tNumpyArrayToString.java src\jep\test\numpy\TestNumpyGILFreeze.java src\jep\test
\numpy\TestNumpyMemoryLeak.java src\jep\test\numpy\TestScipyFreeze.java
copying src\jep\ClassEnquirer.java to build\java\jep.src\jep\ClassEnquirer.java
copying src\jep\ClassList.java to build\java\jep.src\jep\ClassList.java
copying src\jep\InvocationHandler.java to build\java\jep.src\jep\InvocationHandl
er.java
copying src\jep\Jep.java to build\java\jep.src\jep\Jep.java
copying src\jep\JepConfig.java to build\java\jep.src\jep\JepConfig.java
copying src\jep\JepException.java to build\java\jep.src\jep\JepException.java
copying src\jep\JepScriptEngine.java to build\java\jep.src\jep\JepScriptEngine.j
ava
copying src\jep\JepScriptEngineFactory.java to build\java\jep.src\jep\JepScriptE
ngineFactory.java
copying src\jep\NamingConventionClassEnquirer.java to build\java\jep.src\jep\Nam
ingConventionClassEnquirer.java
copying src\jep\NDArray.java to build\java\jep.src\jep\NDArray.java
copying src\jep\Proxy.java to build\java\jep.src\jep\Proxy.java
copying src\jep\Run.java to build\java\jep.src\jep\Run.java
copying src\jep\Util.java to build\java\jep.src\jep\Util.java
copying src\jep\python\PyClass.java to build\java\jep.src\jep\python\PyClass.jav
a
copying src\jep\python\PyModule.java to build\java\jep.src\jep\python\PyModule.j
ava
copying src\jep\python\PyObject.java to build\java\jep.src\jep\python\PyObject.j
ava
copying src\jep\test\Test.java to build\java\jep.test.src\jep\test\Test.java
copying src\jep\test\TestBoxing.java to build\java\jep.test.src\jep\test\TestBox
ing.java
copying src\jep\test\TestGetByteArray.java to build\java\jep.test.src\jep\test\T
estGetByteArray.java
copying src\jep\test\TestMemoryLeaks.java to build\java\jep.test.src\jep\test\Te
stMemoryLeaks.java
copying src\jep\test\numpy\TestNumpy.java to build\java\jep.test.src\jep\test\nu
mpy\TestNumpy.java
copying src\jep\test\numpy\TestNumpyAny.java to build\java\jep.test.src\jep\test
\numpy\TestNumpyAny.java
copying src\jep\test\numpy\TestNumpyArrayToString.java to build\java\jep.test.sr
c\jep\test\numpy\TestNumpyArrayToString.java
copying src\jep\test\numpy\TestNumpyGILFreeze.java to build\java\jep.test.src\je
p\test\numpy\TestNumpyGILFreeze.java
copying src\jep\test\numpy\TestNumpyMemoryLeak.java to build\java\jep.test.src\j
ep\test\numpy\TestNumpyMemoryLeak.java
copying src\jep\test\numpy\TestScipyFreeze.java to build\java\jep.test.src\jep\t
est\numpy\TestScipyFreeze.java
running build_javah
C:\Program Files\Java\jdk1.7.0_67\bin\javah.exe -classpath build\java -o build\i
nclude\jep.h jep.Jep
C:\Program Files\Java\jdk1.7.0_67\bin\javah.exe -classpath build\java -o build\i
nclude\jep_object.h jep.python.PyObject
C:\Program Files\Java\jdk1.7.0_67\bin\javah.exe -classpath build\java -o build\i
nclude\invocationhandler.h jep.InvocationHandler
running build_jar
copying src/jep/classlist_6.txt to build/java\jep\classlist_6.txt
copying src/jep/classlist_7.txt to build/java\jep\classlist_7.txt
copying src/jep/classlist_8.txt to build/java\jep\classlist_8.txt
C:\Program Files\Java\jdk1.7.0_67\bin\jar.exe -cf build/java/jep.src-3.5.0.jar -
C build/java/jep.src jep
C:\Program Files\Java\jdk1.7.0_67\bin\jar.exe -cfe build/java/jep-3.5.0.jar jep.
Run -C build/java/ jep
C:\Program Files\Java\jdk1.7.0_67\bin\jar.exe -cf build/java/jep.test.src-3.5.0.
jar -C build/java/jep.test.src jep
C:\Program Files\Java\jdk1.7.0_67\bin\jar.exe -cfe build/java/jep.test-3.5.0.jar
 test.jep.Test -C build/java/test/ jep
running build_py
running build_ext
building 'jep' extension
error: None

Regards,
Vinoth

**Comment by ndjensen** [comment]
Looks like the comment above moved over to Issue #41.
