### ISSUE TITLE
Error in hook.py module: "string.join" function not exists

### ISSUE THREAD

**Issue by matteozanon** [mrj0/jep#27]
With Python3 the method *join* of module **string** no longer exists.
In the **hook** module this function is used in *load_module* function. 
Quick fix: ```".".join(split[0:-1])``` instead of ```string.join(split[0:-1], ".")```

**Comment by ndjensen** [comment]
Thank you for reporting this and providing a fix.  I've fixed it on _master_ branch.  The unit tests currently stick to the default ClassList and don't really exercise the ClassEnquirer interface.  At some point in time we'll have to add more unit tests.

**Comment by ndjensen** [comment]
This will probably become part of 3.4.2, but I want to wait a bit and see if any other issues are reported in the next week or two with 3.4.

**Comment by ndjensen** [comment]
This is fixed in 3.4.2
