### ISSUE TITLE
Scipy is incompatible

### ISSUE THREAD

**Issue by joeisongit** [mrj0/jep#3]
The problem occurs on ubuntu 12.04, using python 2.7 with the default numpy and scipy packages installed and with Jep 3.1.0.
I try running 

    package applicationtest;
    import jep.Jep;
    import jep.JepException;

    class JepTest {

        public static void main(String[] args)
        {
                try {
                    Jep jep = new Jep(true,".");
                    jep.eval("import sys");
                    jep.eval("a=3");
                    jep.eval("a+=3");
                    jep.eval("print sys.path");
                    jep.eval("import numpy");
                    jep.eval("import scipy");
                    jep.eval("import numpy.random");
                    jep.eval("import scipy.stats");

                    Integer myInt = (Integer)jep.getValue("a");
                    System.out.println(myInt);
                } catch(JepException e) {
                    e.printStackTrace();
                }
        }

    }

The call to PyRun_String when performing jep.eval("import scipy.stats") appears to deadlock.
When I run the script with the PYTHONVERBOSE flag set to 1 it appears that the last attempted import is

# /usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_schur.pyc matches /usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_schur.py
import scipy.linalg.decomp_schur # precompiled from /usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp_schur.pyc

Thanks
Joe

**Comment by ndjensen** [comment]
numpy and scipy should work with Jep 3.3.  I haven't tried out the exact test listed above, but I did discover and resolve issues with Jep and the GIL with numpy.  I'm hoping we can close this with 3.3.

**Comment by ndjensen** [comment]
I tested the provided test case code and verified it's fixed in 3.3.
