### ISSUE TITLE
Request for better threading API

### ISSUE THREAD

**Issue by behdad84** [mrj0/jep#32]
Hi, is it possible to:

1. make some of the private fields and methods of Jep at least protected so a sub-class can override or initialize in different way?
2.  make the thread safety check (via isValidThread) controlled by user set flag?

Here is the problem I have regarding to the second request: I have a spark streaming application in which for every task (there could be a lot of them in a jvm and most f them run sequentially) I make a Jep instance to do some python calls. Every task is a thread. To cache the global space of the script I have to do jep.runScript() once per instance of jep which takes a lot of time. Then when a task is done a new one starts and just because a new task is a basically a new thread I have to close the jep instance and create a new one and do the script global space caching once again . This is taking to much time every time and is really delaying my application. Since in the Spark application I an make sure a jep instance is used only in one thread I would be great to be reusing the same Jep instance for different sequential threads not every-time kill and create a new one.

Thank you very much.

can take care not to instantiate a Jep instance

**Comment by behdad84** [comment]
It would be really great if I could at least have the flag (for making the isValidThread check optional) or making the private Thread thread; public or possibly to set. It is actually a blocker for my code right now.

Thank you very much.

**Comment by ndjensen** [comment]
All the threading limitations with `isValidThread()` are required for Jep to work right.  I agree it's not the most wonderful thing but it's due to limitations with JNI.  Without those checks, all the code will stop working.

I have discussed it briefly with others and it may be theoretically possible to break some of those threading requirements to allow more advanced and more convenient threading paradigms.  But that would require rewriting most of Jep, and then we run the risk of encountering the GIL issues again that Jep instantiation and close() try to protect against.  Not to mention breaking backwards compatibility and introducing risk just due to the amount of changes.

Rewriting the threading paradigm would be considered highly experimental and if successful would warrant a major release change (e.g. Jep 4.0).  I'm still not sure it's even possible and it is not a priority for us.  If you're that interested in it, try forking the project and make some of the changes you're suggesting and see if you can get it to work.  Someone needs to prove it's even feasible before we go too far.

**Comment by behdad84** [comment]
I understand that the check is vital to the correctness of execution; what I am thinking making is exposing the thread field to subclasses (making it protected or settable) so in case which the application itself takes care of all threading constraints, the jep instance be used for a different thread as well. Again the application itself take care of making sure than two threads using the same jep instance won't be executed together. 

(In my specific case, creating and caching the global space of a script to make "invoke" calls is an expensive operation (takes about 12s) while the actual invoke takes about 5 seconds. Right now for every new call I have to create a new jep instance and invoke call the "runScript" which makes it very expensive. Instead I could do it once and just call the invoke since the global space is already cached.)

**Comment by ndjensen** [comment]
Jep is not arbitrarily enforcing threading constraints.  These threading restrictions are coming from trying to be safe with both JNI and CPython.

From [JNI docs](http://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/design.html#wp9502):
> The JNI interface pointer is only valid in the current thread. A native method, therefore, must not pass the interface pointer from one thread to another. A VM implementing the JNI may allocate and store thread-local data in the area pointed to by the JNI interface pointer.

From [CPython docs](https://docs.python.org/2/c-api/init.html#non-python-created-threads):
> However, when threads are created from C (for example by a third-party library with its own thread management), they don’t hold the GIL, nor is there a thread state structure for them.  If you need to call Python code from these threads (often this will be part of a callback API provided by the aforementioned third-party library), you must first register these threads with the interpreter by creating a thread state data structure, then acquiring the GIL, and finally storing their thread state pointer, before you can start using the Python/C API. When you are done, you should reset the thread state pointer, release the GIL, and finally free the thread state data structure.

Jep is trying to manage all of this with the [JepThread struct](https://github.com/mrj0/jep/blob/master/src/jep/pyembed.h#L52).  If you were to change the Thread object inside a Jep instance, you would need to replace the PyThreadState* and JNIEnv* and possibly more inside the JepThread struct.  Even if that works, that can potentially mess up any CPython extensions using the PyGILState_* API.  A notable example is numpy which can deadlock when it encounters a different thread than it was expecting with PyGILState_Ensure().

**As previously stated, someone needs to prove the idea is even feasible.**  Even then, it would require rewriting much of Jep and it's not clear how much value it adds.
