### ISSUE TITLE
new a JEP throws an error 

### ISSUE THREAD

**Issue by mountlovestudy** [mrj0/jep#33]
hi,  
 I just new a Jep like this : Jep jep = new Jep();
 It throws an error:
 java.lang.UnsupportedClassVersionError: jep/Jep : Unsupported major.minor version 52.0
 Any ideas, what wrong might be ?
 thanks a lot

**Comment by ndjensen** [comment]
http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error?lq=1

**Comment by ndjensen** [comment]
If not clear, it appears you compiled Jep with Java 8 but then tried to run with an earlier version.
