### ISSUE TITLE
OverflowError for Python int value in Windows

### ISSUE THREAD

**Issue by matteozanon** [mrj0/jep#36]
The conversion of int value from Python 3.4 to Java in Windows is broken when the number is greater than 2^31-1. The exception thrown is **OverflowError: Python int too large to convert to C long**. The error was first reported here https://groups.google.com/forum/#!topic/jep-project/lUSB534w9ik.
Thanks to @ndjensen a first workaround to fix the issue is the following:
in **util.h** change the code from

    #define PyInt_AsLong(i)                   PyLong_AsLong(i)
    #define PyInt_AS_LONG(i)                  PyLong_AsLong(i)

to

    #define PyInt_AsLong(i)                   PyLong_AsLongLong(i)
    #define PyInt_AS_LONG(i)                  PyLong_AsLongLong(i)

**Comment by ndjensen** [comment]
Fixed on dev_3.4 branch, then merged into master and dev_3.5 branches.  Included in 3.4.3 release, thanks for reporting and testing the issue.
