### ISSUE TITLE
Enable package introspection/walking

### ISSUE THREAD

**Issue by airdrik** [mrj0/jep#4]
A useful feature when using the console would be to be able to type e.g.:
```python
import java.util
```
and then be able to access the packages as well as classes available under java.util e.g. java.util.concurrent, java.util.concurrent.atomic.

Similarly, this should enable such things as:
```python
from java.util import *
```
which would import the sub-packages as well as any classes under that package.

(in my particular use case, I would like a way to import all of the classes in a given package tree, recursively; for simple ease-of-use in stepping into and manipulating java objects that are part of a separate java-only project)

**Comment by ndjensen** [comment]
We should be able to infer sub-packages with the data available in the classlist files.  That probably needs to become part of the `ClassEnquirer` interface somehow so the import hook can get at that data.

**Comment by ndjensen** [comment]
Ok I've got this working on the dev_3.5 branch and it will become part of Jep 3.5 when that is released.  The `ClassList` supports this capability and if someone comes up with a better or different way of supporting this capability, they just have to write the methods on an implementation of the `ClassEnquirer` interface.  Closing as fixed.
