### ISSUE TITLE
release on pypi.python.org comes without jep/src/scripts/jep.bat

### ISSUE THREAD

**Issue by gweidenholzer** [mrj0/jep#44]
Building JEP on windows platform fails, because the released archive jep-3.5.1.tar.gz comes without the batch-file jep/src/scripts/jep.bat

As a workaround you can manually run "python setup.py build" after adding the file https://github.com/mrj0/jep/blob/master/src/scripts/jep.bat

regards,
Günther

**Comment by ndjensen** [comment]
Did you get it from pip or pypi.org?  I always test it from the github source so I probably missed that and it's probably always had that problem since we introduced jep.bat.

**Comment by gweidenholzer** [comment]
Hi Nathan,


jep.bat is missing in the pypi release on https://pypi.python.org/pypi/jep
Now I've seen that the version on github is ok.

Regards,
Günther



2016-04-11 15:29 GMT+02:00 Nathan Jensen <notifications@github.com>:

**Comment by ndjensen** [comment]
Ok I will try and fix that for the next release.

**Comment by ndjensen** [comment]
Fixed in 3.4.4 and 3.5.2.  Merged forward into dev_3.6.
