### ISSUE TITLE
Bundled tests can not run until the just-built files are installed

### ISSUE THREAD

**Issue by UnitedMarsupials** [mrj0/jep#46]
Tests are much more useful, if they can be used to determine the build's validity _before_ installing. Unfortunately, `setup.py test` fails unless jep (of same or _different_ version) is already installed.

Ideally, the script will set the necessary Java and Python environment variables and flags for the `runtests.py` to work from inside the tree prior to installation. Thanks!

**Comment by ndjensen** [comment]
Agreed.  That should be do-able, it just hasn't been a priority yet.

**Comment by ndjensen** [comment]
The workaround for now is to use [virtualenv](https://virtualenv.pypa.io/en/stable/).

**Comment by ndjensen** [comment]
This is fixed on dev_3.6 branch.
