### ISSUE TITLE
Detect absence of JDBC, Numpy, others in tests

### ISSUE THREAD

**Issue by UnitedMarsupials** [mrj0/jep#47]
Currently some of the tests will report failure if JDBC, Numpy or similarly _optional_ dependencies aren't available.

Perhaps, they can be skipped instead of failing with `unittest.skipIf()` conditions?

**Comment by ndjensen** [comment]
The [JDBC test](https://github.com/mrj0/jep/blob/master/tests/test_jdbc.py) has `unittest.skipIf()` but it looks like it only skips if on Windows.  The [numpy test](https://github.com/mrj0/jep/blob/master/tests/test_numpy.py) has some ifs so it's supposed to skip, but it will improperly be marked as passed then and should instead use `unittest.skipIf()` to show that it was skipped.  Both should be cleaned up.  Are you aware of any others besides JDBC and numpy?

Our unit tests in general need cleaned up and more coverage of capabilities.  Feel free to submit pull requests or add comments to this issue for more test improvements.

**Comment by ndjensen** [comment]
I fixed this for JDBC and numpy on dev_3.6 branch.  If there are other optional dependencies, I'm currently unaware of them.  Closing as fixed on 3.6.
