### ISSUE TITLE
Jep Import Error 

### ISSUE THREAD

**Issue by AJF1** [mrj0/jep#48]
Hi there, 

I'm having trouble running the helloWorld example on mac os 10.11.4 (El Capitan) I tried multiple times installing jep from the instructions provided. I am running the example on Eclipse where I have set jep-3.5.2.jar as an external jar and have set JRE Native Library location (jdk1.8.0_91) to the Jep folder as to not get a "java.lang.UnsatisfiedLinkError: no jep in java.library.path" error.  

Any help on the below error would be great. 

Exception in thread "main" jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: No module named jep
	at jep.Jep.eval(Jep.java:485)
	at jep.Jep.<init>(Jep.java:299)
	at jep.Jep.<init>(Jep.java:251)
	at jep.Jep.<init>(Jep.java:228)
	at jep.Jep.<init>(Jep.java:191)
	at org.tests.FirstTest.main(FirstTest.java:9)
Caused by: jep.JepException: <type 'exceptions.ImportError'>: No module named jep

Thanks in advance!

**Comment by ndjensen** [comment]
Did you try running `python setup.py test` and did that work?  Did you try just running the command line jep script that is like a Python interpreter?  That should be located at your pythonInstall/bin.  Please let me know if either or both of those are working or failing so we can try and narrow it down.

**Comment by AJF1** [comment]
So i get the below message from running python setup.py test

$ python setup.py test
numpy include found at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/core/include
running test
jep runtests.py
ImportError: numpy.core.multiarray failed to import

 A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x0000000125876d2c, pid=699, tid=3083

 JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
 C  [jep.so+0x1d2c]  npy_array_check+0x1c

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Users/name/anaconda2/lib/python2.7/site-packages/jep-master/hs_err_pid699.log

_ASIDE: (Will I send the log)_ 

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.
error: command 'jep' terminated by signal 6

================================================================

When I type jep into the terminal, the interpreter starts without any trouble. I am able to run the 'Calling Java constructors/methods from Python' examples. However I was not able to import numpy. Here was the error for this.

>>> import numpy
Traceback (most recent call last):
  File "/Users/name/anaconda2/lib/python2.7/site-packages/jep/console.py", line 71, in prompt
    ran = jep.eval(line)
RuntimeError: jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: dlopen(/Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so, 10): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

**Comment by ndjensen** [comment]
Ok, maybe the numpy install is bad?  Try opening a normal python command line interpreter (not Jep interpreter) and importing numpy there.

**Comment by AJF1** [comment]
Numpy imports fine. I ran some of the tests that came with the multiarray, as that failed to import with jep. It works well apart from this message below. Numpy came part of the anaconda build, maybe installing numpy by itself may work?

$ python test_multiarray.py
............................................................................................................................................................................................................................................................................................................S..................................................../Users/name/anaconda2/lib/python2.7/site-packages/numpy/core/tests/test_multiarray.py:765: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  assert_equal(x == y, False)
/Users/name/anaconda2/lib/python2.7/site-packages/numpy/core/tests/test_multiarray.py:774: FutureWarning: elementwise == comparison failed and returning scalar instead; this will raise an error or perform elementwise comparison in the future.
  assert_equal(x == y, False)
........................................................
----------------------------------------------------------------------
Ran 409 tests in 7.906s

OK (SKIP=1)

**Comment by ndjensen** [comment]
Just so I understand correctly,

- If you run jep inside a Java application, it fails with 'No module named jep'
- If you run the jep tests from the terminal, it fails with the process crashing
- If you run the jep command line interpreter, it works fine unless you import numpy
- If you run the python command line interpreter, numpy imports fine

And you got python from anaconda but you built jep yourself and installed it to the same path as anaconda's python (so site-packages has a jep dir)?  One thing to check in both jep's and python's command line interpreters is sys.path where it looks for imports.  See if those are the same.
```python
import sys
sys.path
```
I should clean up that test so it doesn't crash the process, but I'm perplexed as to the root of your problems.

**Comment by AJF1** [comment]
I have an update but to answer your questions at time of asking

- If you run jep inside a Java application, it fails with 'No module named jep' (Yes)
- If you run the jep tests from the terminal, it fails with the process crashing (Yes)
- If you run the jep command line interpreter, it works fine unless you import numpy (Yes)
- If you run the python command line interpreter, numpy imports fine (Yes)
Very confusing isn't it?

Anyway update! so I decided to run eclipse from the terminal as opposed to opening up the application from the desktop. As a result of this jep is able to be imported and works to an extent. It fails when I want to import numpy. Here is the traceback 


Exception in thread "main" jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: dlopen(/Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so, 10): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

	at jep.Jep.eval(Jep.java:485)
	at org.tests.FirstTest.main(FirstTest.java:12)
Caused by: jep.JepException: <type 'exceptions.ImportError'>: dlopen(/Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so, 10): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

	at /Users/name/anaconda2/lib/python2.7/io.<module>(io.py:51)
	at /Users/name/anaconda2/lib/python2.7/tempfile.<module>(tempfile.py:32)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/testing/utils.<module>(utils.py:15)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/testing/__init__.<module>(__init__.py:14)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/core/__init__.<module>(__init__.py:58)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/lib/type_check.<module>(type_check.py:11)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/lib/__init__.<module>(__init__.py:8)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/add_newdocs.<module>(add_newdocs.py:13)
	at /Users/name/anaconda2/lib/python2.7/site-packages/numpy/__init__.<module>(__init__.py:184)
 

This is very similar to the import error in the jep interpreter:

jep
>>> import numpy
Traceback (most recent call last):
  File "/Users/name/anaconda2/lib/python2.7/site-packages/jep/console.py", line 71, in prompt
    ran = jep.eval(line)
RuntimeError: jep.JepException: jep.JepException: <type 'exceptions.ImportError'>: dlopen(/Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so, 10): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/name/anaconda2/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup


I looked into the sys.path and there is a very slight difference between the paths. In the jep sys.path
 'Users/name/anaconda2/Extras/lib/python' and '.' are paths not in python. '' is the only 'extra' path in the python sys.path not in jep sys.path. Also  'Users/name/anaconda2/Extras/lib/python' does not exist in my file system. 

As it happens I do not need numpy at the moment so there is no hurry but it would be nice to figure out what is causing this. My setup on my mac is fairly minimal so I don't see other applications getting in the way so to be speak.

**Comment by ndjensen** [comment]
Are you using 2.7.10 or 2.7.11?  This appears to be limited to OS X.  See the following links:

1. http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder-trying-to-register-a-packa
1. http://stackoverflow.com/questions/34861128/osx-using-bash-to-find-python-is-different-than-using-usr-bin-env-python
1. http://stackoverflow.com/questions/34589056/conda-and-pip-not-working-at-all

Have you tried the `hash -r python` example?  The first link has the most information.  It also implies if you use 2.7.10 instead of 2.7.11 it is not a problem.  Let me know if you make progress.

**Comment by AJF1** [comment]
2.7.11. 

conda install python=2.7.10 will solve the import numpy problem. I must still run eclipse from the terminal as opposed to just opening it up from the desktop but this is not a major issue at all. 

Jep is now working just fine from what I can see and the problem above was more an OS problem. 

Thank you for the help!

**Comment by ndjensen** [comment]
I don't have Eclipse installed on OS X, but on Linux in Eclipse I go to the Run/Debug configuration of the application, Environment tab, and set PATH and LD_LIBRARY_PATH to make the application work when running from Eclipse.  That way the alteration of PATH and LD_LIBRARY_PATH is limited to only when running within Eclipse.

It looks like OS X has a slightly different variable name: http://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s

**Comment by AJF1** [comment]
I added the PATH variable to the environment tab and everything is working now!

**Comment by ndjensen** [comment]
Great!
