### ISSUE TITLE
Installing Jep on Windows - 1120 link error - Python and JDK versions compatibility

### ISSUE THREAD

**Issue by klesniewski** [mrj0/jep#56]
When trying to install Jep on Windows with `pip install jep`, I encountered a following problem:

```
pyembed.obj : error LNK2019: unresolved external symbol __imp__JNI_GetCreatedJavaVMs@12 referenced in function _pyembed_get_env
build\lib.win32-2.7\jep.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Users\\lesni\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120
```

It turns out, that the problem is with [Java and Python being compiled for different architectures][jdk-python-32-64]] (x86 and x64). In my case, I had 32 bit Python 2.7 and 64 bit JDK 1.8. To solve the problem, I installed Python 2.7 x64 and created virtualenv, which uses the x64 Python version. After that, Jep installed without any problems.

Just leaving it here for others who Google the same problem. You may want to add it to the Wiki.

[jdk-python-32-64]: https://sourceforge.net/p/jepp/mailman/jepp-users/thread/CANOQTQG0oF4nAk%2Bxv3vFag-tEZSYh2wpcD-xABZzqQK5kT7r5Q@mail.gmail.com/

**Comment by ndjensen** [comment]
Thanks for the info.  You can also send an email to the mailing list and that should be found through Google.  Regardless, this should help others.  I don't want to put it on the wiki at this time until we get all the possible variations of the error message which are dependent on operating system and whether the Python is 32 bit and Java 64 bit and vice versa.
