### ISSUE TITLE
No module named _jep

### ISSUE THREAD

**Issue by ctongfei** [mrj0/jep#58]
I used `pip install jep` to install jep.
`import jep` failed: it exits with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/jep/__init__.py", line 2, in <module>
    from _jep import *
ImportError: No module named _jep
```

**Comment by ndjensen** [comment]
https://groups.google.com/forum/#!topic/jep-project/n69BIlpU4ls

jep cannot be imported from a Python process.  A Java process must start the Python interpreter, i.e. Jep must be used from Java, either within your Java application or with the jep script.  The error message has been improved for the next release of Jep.
