### ISSUE TITLE
Error loading python logging module

### ISSUE THREAD

**Issue by shreyastp** [mrj0/jep#63]
i have created a maven project. I have installed jepp under python/site packages.But when i try run the python programs from jepp not able to run. Can you please help me 

camelot.utils.vapi_ei_utils
Dec 05, 2016 7:41:31 PM com.cisco.ccbu.cvp.automation.callflow.phonesimulator.Main main
SEVERE: null
jep.JepException: <type 'exceptions.ImportError'>: logging.getLogger
	at C:\Python27\lib\site-packages\jep\java_import_hook.__getattr__(java_import_hook.py:32)
	at C:\Python27\lib\site-packages\camelot_pi-11.5.0.0.24.1-py2.7.egg\camelot\camlogger.getLogger(camlogger.py:48)
	at C:\Python27\lib\site-packages\camelot_pi-11.5.0.0.24.1-py2.7.egg\camelot\utils\vapi_ei_utils.<module>(vapi_ei_utils.py:9)
	at C:\Python27\lib\site-packages\camelot_pi-11.5.0.0.24.1-py2.7.egg\camelot\__init__.<module>(__init__.py:6)
Caused by: java.lang.ClassNotFoundException: logging.getLogger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at jep.Jep.eval(Native Method)
	at jep.Jep.eval(Jep.java:571)
	at com.cisco.ccbu.cvp.automation.callflow.phonesimulator.Main.executeCommand(Main.java:47)
	at com.cisco.ccbu.cvp.automation.callflow.phonesimulator.Main.main(Main.java:32)

**Comment by ndjensen** [comment]
Your stacktrace implies that Jep tried to import the python logging module (specifically logging.getLogger) as a Java import.  The ClassEnquirer which is on java_import_hook.py line 31 should be returning false since it's a Python package.  Are you using a custom ClassEnquirer that returns true for logging.getLogger?

**Comment by shreyastp** [comment]
Thanks for the reply no i am not using any custom ClassEnquirer

**Comment by ndjensen** [comment]
Does your Java classpath have a package starting with the word `logging`?  That could also cause this error.

**Comment by shreyastp** [comment]
sorry for the delayed reply . no i don't have any package starting with word logging. however there are class files with logging which is included from JRE

**Comment by bsteffensmeier** [comment]
I would recommend that you specify a class enquirer that does not include logging. The simplest thing to do is probably to just use the NamingConventionClassEnquirer which has some reasonable defaults for what java packages to allow in python and does not include logging.

If this conflict is occurring without a custom logging package that is specific to your project then we may want to update the default class enquirer to exclude logging from the python imports but before we can do that we need to understand where the logging package is coming from in java. I do not have classfiles in the logging package in my JRE, can you elaborate on what version of the JRE you are using and what class files you see that have logging in the package?

It may help if you can get information on what is in the logging module. When you create your Jep instance can you eval these two lines of python to see what is in the logging module:
```python
import logging
print(dir(logging))
```

**Comment by shreyastp** [comment]
Hi here is output for what you have asked for.
objJep.eval("import logging");
objJep.eval("print(dir(logging))");

Output

['config$py', 'handlers$py']  
Succedded
<class 'jep.java_import_hook.module'> shreyas getLoggerClass
not succeeded
jep.java_import_hook getLoggerClass Inside java hook

**Comment by shreyastp** [comment]
the actual =output when executed from a python shell is somewhat like this

'BASIC_FORMAT', 'BufferingFormatter', 'CRITICAL', 'DEBUG', 'ERROR', 'FATAL', 'FileHandler', 'Filter', 'Filterer', 'Formatter', 'Handler', 'INFO', 'LogRecord', 'Logger', 'LoggerAdapter', 'Manager', 'NOTSET', 'NullHandler', 'PlaceHolder', 'RootLogger', 'StreamHandler', 'WARN', 'WARNING', '__all__', '__author__', '__builtins__', '__date__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__status__', '__version__', '_acquireLock', '_addHandlerRef', '_checkLevel', '_defaultFormatter', '_handlerList', '_handlers', '_levelNames', '_lock', '_loggerClass', '_releaseLock', '_removeHandlerRef', '_showwarning', '_srcfile', '_startTime', '_unicode', '_warnings_showwarning', 'addLevelName', 'atexit', 'basicConfig', 'cStringIO', 'captureWarnings', 'codecs', 'collections', 'critical', 'currentframe', 'debug', 'disable', 'error', 'exception', 'fatal', 'getLevelName', 'getLogger', 'getLoggerClass', 'info', 'log', 'logMultiprocessing', 'logProcesses', 'logThreads', 'makeLogRecord', 'os', 'raiseExceptions', 'root', 'setLoggerClass', 'shutdown', 'sys', 'thread', 'threading', 'time', 'traceback', 'warn', 'warning', 'warnings', 'weakref']

**Comment by bsteffensmeier** [comment]
It looks like you are running jython in the same JVM as jep. The default class enquirer will not work in this case because many jython java packages will conflict with python modules. The combination of Jep and Jython is not something that we test or support but it looks like it may work if you use a custom class enquirer.

**Comment by shreyastp** [comment]
how should  i use a custom class enquirer . can u please explain me how i can do this i am not aware of this

**Comment by bsteffensmeier** [comment]
To use a custom class enquirer you just need to set it up on the jep config when you construct your jep instance:
```java
new Jep(new JepConfig().setClassEnquirer(new NamingConventionClassEnquirer()));
```

As I mentioned earlier, I suspect the existing NamingConventionClassEnquirer will work for you since it is more restrictive than the default but depending on what python/java modules you may need more fine tuning which would require you to write a new class enquirer.

**Comment by ndjensen** [comment]
Look at the javadoc for Jep's interface ClassEnquirer. Implement the interface with your own code if one of the provided ones does not do what you need.
