### ISSUE TITLE
Use some more reliable way to locate jep.jar

### ISSUE THREAD

**Issue by liangent** [mrj0/jep#7]
In my system, jep.jar is installed to /usr/local/lib/jep/jep.jar. However jep command (/usr/local/bin/jep) contains cp="/usr/lib/jep/jep.jar", causing jep.Run not found.

**Comment by divad** [comment]
I have hit this issue as well.

**Comment by ndjensen** [comment]
Are you also on Debian?

**Comment by divad** [comment]
Ubuntu 14.04 (so..yes :P)

**Comment by ndjensen** [comment]
Ok I traced this to the fact that we install the jar using distutil's install_data, but we do fancier stuff for figuring out the lib dir for installing libjep.so.  On Ubuntu/Debian it appears the two dirs don't match up whereas on most platforms they do.  I've fixed it on 3.3.4 and uploaded it to pypi.  Someone want to give it a try?

**Comment by ndjensen** [comment]
Tested on a virtual machine Ubuntu and it worked.  Closing as fixed in 3.3.4.
