### ISSUE TITLE
A little question about jep.jar

### ISSUE THREAD

**Issue by Heidernlee** [mrj0/jep#70]
So excited to see the package you provided.
And now I have a question about whether I can get jep.jar after we suuccessful install Python.
The situation is I couldn't install this jep package because of many Python Env. Problems(may be),
and couldn't get jep.jar
So, can u provide jep.jar for me ? I hope to import it with my Eclipse（JDK1.8）.
Thank u for reading!

**Comment by ndjensen** [comment]
You need to download jep and then run `python setup.py build` and it will produce the jep jar for you in the build directory.

**Comment by Heidernlee** [comment]
Thanks for your replay.
Yes, but many issues occurred while running [setup.py] on my computer,
as all my project need is jep.jar, could you please provide jar file ?

**Comment by ndjensen** [comment]
The jar is useless without the native library.  Furthermore, the Jep jar version needs to match the native library version.  If you can't get the build with `python setup.py build` you've got bigger problems.
