### ISSUE TITLE
Getting error while using deep copy.

### ISSUE THREAD

**Issue by Vkynluv** [mrj0/jep#73]
num = 6
SG=np.empty((num),dtype=object)
SG=[0.001,0.002,0.003,0.004,0.005,0.006]
SG1=np.empty((num),dtype=object)
for tempv in range(0,6):
    for tempt in range(tempv+1,6):
        if SG[tempv]==SG[tempt]:
            SG[tempt]=SG[tempt]+0.000001
SG1=deepcopy(SG)

While executing this code. This exception is thrown
jep.JepException: jep.JepException: <class 'copy.Error'>: un(deep)copyable object of type <class 'jep.PyJNumber'>

**Comment by ndjensen** [comment]
1. Can you please not open a github issue when you don't understand something?  Questions belong on the mailing list (or stackoverflow).  This is unproven to be an issue.  I see you opened a question on stackoverflow so don't open a github issue.  http://stackoverflow.com/questions/43274372/error-while-using-deep-copy-in-python-jepp
2. Can you please use github's tools for code formatting to make the code readable?  I have to guess at your indentation.  https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
3. The code you listed is pure Python.  There is nothing about Jep usage in your example code except the error.  I can run the code you listed in the Python interpreter or in the Jep interpreter.  Both can be used from the command line, e.g. type `python` or `jep`.
4. You're not actually using numpy in the example.  Your arrays are thrown away when you redeclare them with the `=` operator.  Example of the way the code should look:
```Python
from copy import deepcopy
num = 6
sg = [0.001, 0.002, 0.003, 0.004, 0.005, 0.006]
for tempv in range(0, 6):
    for tempt in range(tempv + 1,6):
        if sg[tempv] == sg[tempt]:
             sg[tempt] = sg[tempt] + 0.000001
sg1 = deepcopy(sg)
```

**Comment by bsteffensmeier** [comment]
Without more information there is nothing we can do. There is no evidence this is a bug in jep.
