### ISSUE TITLE
Tests importing jep_pipe fail in Debian stretch

### ISSUE THREAD

**Issue by eastcirclek** [mrj0/jep#84]
After upgrading to Debian stretch from jessie, "python setup.py tests" fails with the following errors. Specifically I'm building a Docker image in which I build Jep. The base image of my Docker image is openjdk:8-jdk and it recently changes its base image from jessie to stretch. 

The errors all stem from trying to import ./tests/jep_pipe using "from tests.jep_pipe import jep_pipe".
When I modify test files to do "from jep_pipe import jep_pipe", the error messages are gone.  

Error messages:

ERROR: test_getvalue (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_getvalue
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 430, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/jep/tests/test_getvalue.py", line 3, in <module>
    from tests.jep_pipe import jep_pipe
ModuleNotFoundError: No module named 'tests.jep_pipe'

ERROR: test_iterators (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_iterators
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 430, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/jep/tests/test_iterators.py", line 3, in <module>
    import tests.jep_pipe
ModuleNotFoundError: No module named 'tests.jep_pipe'

ERROR: testSetGet (test_numpy.TestNumpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/jep/tests/test_numpy.py", line 25, in testSetGet
    from tests.jep_pipe import build_java_process_cmd
ModuleNotFoundError: No module named 'tests.jep_pipe'

ERROR: test_preinits (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_preinits
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 430, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/jep/tests/test_preinits.py", line 3, in <module>
    from tests.jep_pipe import jep_pipe
ModuleNotFoundError: No module named 'tests.jep_pipe'

ERROR: test_run_script (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_run_script
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 430, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/jep/tests/test_run_script.py", line 5, in <module>
    from tests.jep_pipe import jep_pipe
ModuleNotFoundError: No module named 'tests.jep_pipe'

ERROR: test_shared_modules (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_shared_modules
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 430, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/miniconda/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/opt/jep/tests/test_shared_modules.py", line 5, in <module>
    import tests.jep_pipe
ModuleNotFoundError: No module named 'tests.jep_pipe'

----------------------------------------------------------------------
Ran 147 tests in 0.408s

FAILED (errors=6, skipped=12)

**Comment by ndjensen** [comment]
Do you know what changed from Debian 8 (jessie) to Debian 9 (stretch)?  The tests at present work on python 3.6 so I don't understand why it would stop working.  Is it a miniconda thing?

I can certainly change it as long as it doesn't have adverse effects on a different version of Python or operating system.

**Comment by bsteffensmeier** [comment]
I suspect that there is another tests module on the python path that is being used in place of the jep tests module. @eastcirclek can you try importing tests in a regular python and in a jep interactive interpreter and see where the module is loaded from, something like

```python
import tests
print(tests.__file__)
```

**Comment by eastcirclek** [comment]
@bsteffensmeier 
You're right. I've never thought that approach. 

**[with a regular python]**
>  (root) root@62af92774df5:/opt/jep# python
>> import tests
>> print(tests.__file__)
>>> /opt/jep/tests/__init__.py

**[with Jep interactive interpreter]**
> (root) root@62af92774df5:/opt/jep# jep
>> import tests
>> print(tests.__file__)
>>> /opt/miniconda/lib/python3.6/site-packages/tests/__init__.py

@ndjensen 
I found that the source of this problem is keras==2.0.6, not upgrading to stretch. /opt/miniconda/lib/python3.6/site-packages/tests is created when keras==2.0.6 is installed. "pip uninstall keras==2.0.6" will show you a list of files to be deleted and you can files under the tests directory. 

This must be a mistake from keras community. I report this issue to my colleague who contributes to keras. Nevertheless, should Jep cope with such problem?

**Comment by eastcirclek** [comment]
Anyway, fchollet fixes this bug. I close this issue.

**Comment by ndjensen** [comment]
@eastcirclek, I think your suggested imports are more correct.  I tested with travisCI and appveyor and it seems to work fine, so I put it in dev_3.7.
